Title = "TTT"
NewGame = "New Game"
GameTitle = "Game {{.arg1}}"
WaitOtherMessage = "Wait others!"
PlayMessage = "Play!"
CreateAction = "Create"
JoinAction = "Join"
StartAction = "Start"
LeaveAction = "Leave"
NewGameAction = "New Game"
PlayerWin = "Wins!"
PlayerTie = "Tie!"
PlayerLoose = "Looses!"
YouWin = "You wins!"
YouTie = "Tie!"
YouLoose = "You looses!"
Error = "Error: {{.arg1}}!"
PlayerWaitingToJoin = "Waiting..."
PlayerWaitingToStart = "Start?"
PlayerWaitingToPlay = "Waiting..."
PlayerPlaying = "Playing {{.arg1}}..."
PlayerDisconnected = "Disconnected..."
YouWaitingToJoin = "Wait others!"
YouWaitingToStart = "Start?"
YouWaitingToPlay = "Wait!"
YouPlaying = "Play {{.arg1}}!"
YouDisconnected = "Disconnected..."

Hello = "Hello"
[Example]
description = "The number of unread emails I have"
one = "I have {{.PluralCount}} unread email."
other = "I have {{.PluralCount}} unread emails."