Title = "Tic Tac Toe"
Lobby = "Salle d'attente"
NewGame = "Nouvelle Partie"
GameTitle = "Partie {{.arg1}}"
CreateAction = "Créer"
JoinAction = "Rejoindre"
StartAction = "Démarrer"
LeaveAction = "Quitter"
NewGameAction = "Nouvelle Partie"
PlayerWin = "a gagné!"
PlayerTie = "Égalité!"
PlayerLoose = "a perdu!"
YouWin = "Tu as gagné!"
YouTie = "Égalité!"
YouLoose = "Tu as perdu!"
Error = "Erreur: {{.arg1}}!"
PlayerWaitingToJoin = "Attend un autre..."
PlayerWaitingToStart = "C'est parti?"
PlayerWaitingToPlay = "vous attend..."
PlayerPlaying = "Joue {{.arg1}}..."
PlayerDisconnected = "Déconnecté..."
YouWaitingToJoin = "Attends un joueur!"
YouWaitingToStart = "C'est parti?"
YouWaitingToPlay = "Attends ton tour!"
YouPlaying = "À votre tour!"
YouDisconnected = "Déconnecté..."

[Example]
description = "The number of unread emails I have"
one = "J'ai {{.PluralCount}} email non lu."
other = "J'ai {{.PluralCount}} emails non lus."