Title = "TTT"
NewGame = "Nouvelle Partie"
GameTitle = "Partie {{.arg1}}"
WaitOtherMessage = "Attendez!"
PlayMessage = "Jouez!"
CreateAction = "Créer"
JoinAction = "Rejoindre"
StartAction = "Démarrer"
LeaveAction = "Partir"
NewGameAction = "Nouvelle Partie"
PlayerWin = "a gagné!"
PlayerTie = "égalité!"
PlayerLoose = "a perdu!"
YouWin = "Vous avez gagné!"
YouTie = "égalité!"
YouLoose = "Vous avez perdu!"
Error = "Erreur: {{.arg1}}!"
PlayerWaitingToJoin = "Attend un autre joueur..."
PlayerWaitingToStart = "On démarre?"
PlayerWaitingToPlay = "Attend..."
PlayerPlaying = "Joue {{.arg1}}..."
PlayerDisconnected = "Déconnecté..."
YouWaitingToJoin = "Attendez un autre joueur!"
YouWaitingToStart = "On démarre?"
YouWaitingToPlay = "Attendez!"
YouPlaying = "Jouez {{.arg1}}!"
YouDisconnected = "Déconnecté..."

Hello = "Bonjour!"
HelloPerson = "Bonjour {{.Name}}!"
MissingEnglish = "Anglais manquant {{.Name}}"

[Example]
description = "The number of unread emails I have"
one = "J'ai {{.PluralCount}} email non lu."
other = "J'ai {{.PluralCount}} emails non lus."