Title = "Skyjo"
Lobby = "Lobby"
NewGame = "New Game"
GameTitle = "Game {{.arg1}}"
CreateAction = "Create"
JoinAction = "Join"
StartAction = "Start"
LeaveAction = "Leave"
NewGameAction = "New Game"
PlayerWin = "Wins!"
PlayerTie = "Tie!"
PlayerLoose = "Looses!"
YouWin = "You wins!"
YouTie = "Tie!"
YouLoose = "You looses!"
Error = "Error: {{.arg1}}!"
PlayerWaitingToJoin = "Waiting..."
PlayerWaitingToStart = "Start?"
PlayerWaitingToPlay = "Waiting..."
PlayerPlaying = "Playing {{.arg1}}..."
PlayerDisconnected = "Disconnected..."
PlayerPlayed = "has finished"
YouWaitingToJoin = "Wait others!"
YouWaitingToStart = "Start?"
YouWaitingToPlay = "Wait!"
YouPlaying = "Play {{.arg1}}!"
YouPlayed = "End"
YouDisconnected = "Disconnected..."

PlayerHasDrawn = "Has drawn a {{ .card }}"
PlayerHasDiscarded = "Has discarded a {{ .card }}"
PlayerHasPut = "Has put a {{ .card }}"

YouDrawing = "Draw a card"
YouPutting = "Put the {{ .card }}"
YouPuttingOrDiscarding = "Put or discard the {{ .card }}"
YouFlipping = "Flip one card"