Title = "Skyjo"
Lobby = "Salle d'attente"
NewGame = "Nouvelle Partie"
GameTitle = "Partie {{.arg1}}"
CreateAction = "Créer"
JoinAction = "Rejoindre"
StartAction = "Démarrer"
LeaveAction = "Quitter"
NewGameAction = "Nouvelle Partie"
PlayerWin = "a gagné!"
PlayerTie = "Égalité!"
PlayerLoose = "a perdu!"
YouWin = "Tu as gagné!"
YouTie = "Égalité!"
YouLoose = "Tu as perdu!"
Error = "Erreur: {{.arg1}}!"
PlayerWaitingToJoin = "Attend un autre..."
PlayerWaitingToStart = "C'est parti?"
PlayerWaitingToPlay = "vous attend..."
PlayerPlaying = "Joue {{.arg1}}..."
PlayerDisconnected = "Déconnecté..."
PlayerPlayed = "a fini"
YouWaitingToJoin = "Attends un joueur!"
YouWaitingToStart = "C'est parti?"
YouWaitingToPlay = "Attends ton tour!"
YouPlaying = "À ton tour!"
YouPlayed = "C'est fini"
YouDisconnected = "Déconnecté..."

PlayerHasDrawn = "A pris un {{ .card }}"
PlayerHasDiscarded = "A jeté un {{ .card }}"
PlayerHasPut = "A posé un {{ .card }}"

YouDrawing = "Piochez une carte"
YouPutting = "Posez le {{ .card }}"
YouPuttingOrDiscarding = "Posez ou jetez le {{ .card }}"
YouFlipping = "Retournez une carte"