Title = "50 Missions"
Lobby = "Lobby"
NewGame = "New Game"
GameTitle = "Game {{.arg1}}"
CreateAction = "Create"
JoinAction = "Join"
StartAction = "Start"
LeaveAction = "Leave"
NewGameAction = "New Game"