Title = "50 Missions"
Lobby = "Salle d'attente"
NewGame = "Nouvelle Partie"
GameTitle = "Partie {{.arg1}}"
CreateAction = "Créer"
JoinAction = "Rejoindre"
StartAction = "Démarrer"
LeaveAction = "Quitter"
NewGameAction = "Nouvelle Partie"